### ISSUE TITLE
Title + Meta Description and Hackathon List Page Shallow Routing

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#45]
When a webpage is rendered (Let's say a hackathon detail page). It renders with the title `hackathon -` after the data is fetched from the backend, the hackathon slug is added to this string. Also, the description in meta is showed as undefined.

### Update

This issue now deals with the following points:
- [ ] The meta description can be made to vary with the hackathon details like "Register for {hackathon name} at COPS Hackalog, {hackathon tagline}" on `hackathon/[slug]`.
- [ ] On the `/submission/[id]` page, description meta can be the submission's description and some placeholder while loading.
- [ ] On the `/hackathons` page, we can change the title as the tabs change. So maybe like "Ongoing Hackathons" instead of "Hackathons" when the ongoing tab is opened.
- [ ] On the `/profile` page, we can use the "About Me" of the user as the meta description; the current `{User's Name}'s Profile on COPS Hackalog, a platform for organising hackathons` looks kinda irrelevant.
- [ ] Change the url as the tabs change. Ex - `/hackathons/?tab=ongoing`. For this, we need a controlled tab component. (ref: [here](https://react-bootstrap.github.io/components/tabs/))

To access the url parameters, we'd need `router.query`, which is already used in some dynamic pages (for reference). Below are the links for documentation:
- Dynamic Routes: https://nextjs.org/docs/routing/dynamic-routes
- Shallow Routing (to update the route) https://nextjs.org/docs/routing/shallow-routing

**Comment by ujju20** [comment]
I am taking up this issue. Can you explain this briefly?

**Comment by shubhanshu02** [comment]
This issue needs some discussion since the priorities have changed since the issue was opened. Also, the title part was fixed by some commit earlier. I'll post the relevant parts of this issue in some time today for discussion.

**Comment by shubhanshu02** [comment]
Here are my findings for this issue.
1. The meta description can be made to vary with the hackathon details like "Register for {hackathon name} at COPS Hackalog, {hackathon tagline}" on `hackathon/[slug]`.
2. On the `/submission/[id]` page, description meta can be the submission's description and some placeholder while loading.
3. On the `/hackathons` page, we can change the title as the tabs change. So maybe like "Ongoing Hackathons" instead of "Hackathons" when the ongoing tab is opened.
4. On the `/profile` page, we can use the "About Me" of the user as the meta description; the current `{User's Name}'s Profile on COPS Hackalog, a platform for organising hackathons` looks kinda irrelevant.

@king-11 @subodhk01 @nishantwrp @m-e-l-u-h-a-n, any corrections or suggestions?

**Comment by nishantwrp** [comment]
LGTM.

Just one suggestion for point 3. We can also change the url as the tabs change. Ex - /hackathons/?tab=ongoing

**Comment by subodhk01** [comment]
Looks good!

**Comment by ujju20** [comment]
For solving this issue I think I need to know about next.js. I know js but don't know about next.js can you tell me from where I can learn about it.

**Comment by shubhanshu02** [comment]
The first four do not require Next.js knowledge as such. You may view the `<Head />` element used in files in the `/pages` directory and its documentation [here](https://nextjs.org/docs/api-reference/next/head).

For the last one, you will require Next.js. IMO the best resource for learning Next.js is the [official documentation](https://nextjs.org/docs/getting-started). Some good courses include [Frontend Masters](https://frontendmasters.com/courses/next-js/) (you may need GitHub Student Plan to access it) and [The Net Ninja](https://www.youtube.com/playlist?list=PL4cUxeGkcC9g9gP2onazU5-2M-AzA8eBw) on YouTube.
