### ISSUE TITLE
Migrate Frontend Components to TypeScript

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-frontend#93]
Migrate the JavaScript modules to TypeScript. 

### Files

- [x] context/auth.js (#102)
- [x] components/Header/Header.js (#122)
- [x] components/HackathonCard/HackathonCard.js (#115)
- [x] components/Sorry/Sorry.js (#103)
- [x] components/Footer/Footer.js  (#104)
- [x] components/Date/Date.js (#112)
- [x] components/Cards/Card.js (#108)
- [x] components/Buttons/IconsButton.js (#120)
- [x] components/Clipboard/Clipboard.js (#125)
- [x] components/Profile/index.js (#111)
- [x] components/Profile/Interests.js (#107 )
- [x] components/Profile/ProfileTabs.js (#103)
- [x] components/Profile/EditProfileModal.js (#113)
- [X] components/Profile/TeamCard.js (Fixed by #94)
- [x] components/Profile/SkillOptions.js (#126)
- [x] util/constants.js (#103)
- [x] util/axios.js (#103)
- [x] pages/index.js (#124 )
- [x] pages/submission/[id].js (#102)
- [x] pages/hackathons.js (#114)
- [x] pages/_app.js (#110)
- [x] pages/profile/[username].js (#117)
- [x] pages/hackathon/[slug]/index.js (#123)
- [x] pages/hackathon/[slug]/teams/[team_id]/index.js
- [x] pages/hackathon/[slug]/teams/[team_id]/submit.js (#118)
- [x] pages/hackathon/[slug]/register.js (#116)
- [x] pages/contributors.js (#106)
- [x] pages/_document.js (#109)
- [x] #97

### Steps to follow
1. Rename the file to .tsx or .ts extension as required.
2. Look for the source of props in the component, if required.
3. If the data was obtained from the backend, look for the response type in the backend, using the below list. The response types of each serializer have been added to the `/types/backend.ts`.
4. Migrate to TypeScript.

Backend: https://cops-hackalog.herokuapp.com/
Serializer List and Types for the Backend: https://hackalog-docs.vercel.app/#/serializers

Note: An example of one such migration is in fbbad4c.

### Points to be noted

- Some files only store data and functions, so interfaces are to be made accordingly.
- Add the types to the folder `/types/` to a new file as required. If the same types were already created, prefer reusing them.
- You may need to check the [backend API](https://cops-hackalog.herokuapp.com/) for getting the object types for responses.

### Some Links that may be useful

https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/basic_type_example/
https://www.typescriptlang.org/docs/handbook/intro.html

**Comment by tiger-yash** [comment]
Working on  pages/contributors.js.

**Comment by AG-7219** [comment]
Working on components/HackathonCard/HackathonCard.js

**Comment by soumyo123-prog** [comment]
working on context/auth.js

**Comment by Prakhar-Agarwal-byte** [comment]
Working on components/Cards/Card.js

**Comment by ankur12-1610** [comment]
Wokring on  components/Cards/Card.js

**Comment by try-catch-stack** [comment]
Working on components/Profile/ProfileTabs.js

**Comment by shubhangi013** [comment]
working on components/Profile/Interests.js

**Comment by sahilsaini110** [comment]
Working on components/Clipboard/Clipboard.js

**Comment by shukapurv** [comment]
Working on components/Footer/Footer.js

**Comment by try-catch-stack** [comment]
Working on components/Profile/EditProfileModal.js

**Comment by JeeveshGarg** [comment]
Working on pages/Profile

**Comment by ankur12-1610** [comment]
Working on components/Date/Date.js

**Comment by garimavs** [comment]
Working on components/Profile/SkillOptions.js

**Comment by Tarun-Arora** [comment]
Working on components/Sorry/Sorry.js

**Comment by Tarun-Arora** [comment]
Working on components/Profile/ProfileTabs.js

**Comment by shukapurv** [comment]
Working on components/Header/Header.js

**Comment by Tarun-Arora** [comment]
Working on util/constants.js

**Comment by Tarun-Arora** [comment]
Working on util/axios.js

**Comment by Prakhar-Agarwal-byte** [comment]
Working on pages/_document.js

**Comment by Prakhar-Agarwal-byte** [comment]
Working on pages/_app.js

**Comment by tiger-yash** [comment]
Working on components/Buttons/IconsButton.js

**Comment by tiger-yash** [comment]
Working on pages/index.js

**Comment by Prakhar-Agarwal-byte** [comment]
Working on components/Profile/index.js

**Comment by Prakhar-Agarwal-byte** [comment]
Working on pages/hackathons.js

**Comment by soumyo123-prog** [comment]
working on 
- pages/submission/[id].js 
- pages/hackathon/[slug]/index.js

**Comment by Prakhar-Agarwal-byte** [comment]
Working on

- pages/hackathon/[slug]/teams/[team_id]/submit.js

- pages/hackathon/[slug]/register.js

**Comment by soumyo123-prog** [comment]
The file `pages/hackathon/[slug]/teams/[team_id]/index.js` requires you to be a previous participant for testing purposes (in order to open the page and test it fully). I was woking on it but IG a previous participant of debug-it should take it.
